### ISSUE TITLE
Sleigh raised a bad data exception

### ISSUE THREAD

**Issue by Boyan-MILANOV** [trailofbits/maat#109]
### Discussed in https://github.com/trailofbits/maat/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **infinitesteps** June  7, 2022</sup>
I am just getting started with Maat. I get the following error when trying to execute a function:

```
FATAL: Error in sleigh translate(): Sleigh raised a bad data exception: r0x00000002: Unable to resolve constructor
[Fatal] Lifter error: MaatEngine::run(): failed to lift instructions
```
The target binary is generated from the following code:

```c
#include <stdio.h>

int foo(int a) {
    int c, b = 7;

    c = a * b;

    if (c == 14) {
        printf("FAIL\n");
    } else {
        printf("OK\n");
    }

    return c;
}

int main(int args, char **argv) {
	printf("%d\n", foo(4));
	printf("%d\n", foo(2));
	return 0;
}
```

My Python looks like the following. The address `0x1169` corresponds to the foo function.

```python
from maat import MaatEngine, ARCH, OS, BIN

engine = MaatEngine(ARCH.X64, OS.LINUX)
libdirs = ['/usr/lib64']
libdirs.append('/usr/lib/x86_64-linux-gnu')
engine.load('data/1.elf', BIN.ELF64, libdirs=libdirs)
engine.settings.log_insts = True
stop = engine.run_from(0x1169)
```
</div>

**Comment by Boyan-MILANOV** [comment]
I've tried running the binary without the `libc` but it aborts at the first `printf` call (because the function was not loaded) before the bug is triggered. I am guessing that the unsupported instruction is part of the `libc` code.

Would you mind also sending me the `libc.so` file that is loaded along with `1.elf` ? You can get the path to `libc` by running `ldd 1.elf`. Thanks!

**Comment by infinitesteps** [comment]
Here is my libc...

[libc.so.zip](https://github.com/trailofbits/maat/files/8863970/libc.so.zip)

**Comment by Boyan-MILANOV** [comment]
I've been able to reproduce your issue. The problem comes from the fact that the script starts executing `foo` without executing the loader nor initialising the `libc`. Therefore while executing `printf` it tries to jump to some uninitialised null pointer, as the execution trace shows: 
````
[Info] Run 0x56439e: MOV R15,qword ptr [0x5f0df0]
[Info] Run 0x5643a5: MOV qword ptr [RSP + 0x8],RCX
[Info] Run 0x5643aa: LEA RDI,[R15 + 0x908]
[Info] Run 0x5643b1: CALL qword ptr [R15 + 0xf08]    <---- this jumps to 0x00000000
FATAL: Error in sleigh translate(): Sleigh raised a bad data exception: r0x00000002: Unable to resolve constructor
[Fatal] Lifter error: MaatEngine::run(): failed to lift instructions
````

Since you load the binary at address `0`, branching to `0` doesn't cause an unmapped-memory access error, and Maat tries to disassemble it as code. Since it probably contains illegal instructions, that leads to a sleigh error.

What happens if you run everything from the loader? Like so: 
```python
from maat import MaatEngine, ARCH, OS, BIN

engine = MaatEngine(ARCH.X64, OS.LINUX)
engine.load('data/1.elf', BIN.ELF64, libdirs=['/usr/lib64', '/usr/lib/x86_64-linux-gnu'])
engine.settings.log_insts = True
stop = engine.run()
```

**Comment by Boyan-MILANOV** [comment]
**Note**: I'd still like to make a PR to improve handling of sleigh errors before closing this issue

**Comment by Boyan-MILANOV** [comment]
I'm closing this since it seems to have been resolved. @infinitesteps: please re-open if you run into this again
