### ISSUE TITLE
Error when calling event callbacks 

### ISSUE THREAD

**Issue by Boyan-MILANOV** [trailofbits/maat#130]
Discussed in #125.

It seems that calling event callbacks with Python 3.10 results in a `<callback_name> takes 1 positional argument but 2 were given` error. Something probably changed in the `PyCallable` C API

**Comment by Boyan-MILANOV** [comment]
After more testing it seems that the issue is also present with python `3.8` and `3.9` for @Filippo1205. However everything works for me locally (with `3.9` on macOS, installed with `homebrew`), as well as in the CI.

**Comment by Filippo1205** [comment]
Installing pymaat 0.6.3 the problem "<callback_name> takes 1 positional argument but 2 were given" seems solved, i tried with python3.8, python3.9 and python3.10.
