### ISSUE TITLE
Unexpected behaviour when setting access permissions to PROT_NONE on allocated memory.

### ISSUE THREAD

**Issue by jamesd90** [trailofbits/maat#147]
It looks like Maat doesn't distinguish between unallocated memory and pages with PROT_NONE access permissions. I noticed this when running a binary that can create guard pages for heap allocations.

Basic test:
```
#include <stdio.h>
#include <sys/mman.h>

int main(int argc, char** argv)
{
    void* p = NULL;

    for (int i = 0; i < 10; i++)
    {
        p = mmap(NULL, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, 0, 0);
        printf("%p\n", p);
        mprotect(p, 0x1000, PROT_NONE);
    }

    return 0;
}
```
Sample output (when run normally):
```
0x7fe902ca1000
0x7fe902c74000
0x7fe902c73000
0x7fe902c72000
0x7fe902c71000
0x7fe902a7c000
0x7fe902a7b000
0x7fe902a7a000
0x7fe902a79000
0x7fe902a78000
```
Sample output (when run via Maat):
```
[Info] Adding object 'ld-linux-x86-64.so.2' to virtual fs at '/usr/lib/ld-linux-x86-64.so.2'
[Info] Adding object 'libc.so.6' to virtual fs at '/usr/lib/libc.so.6'
[Info] Adding object './test.bin' to virtual fs at '/./test.bin'
0x41f4000
0x41f4000
0x41f4000
0x41f4000
0x41f4000
0x41f4000
0x41f4000
0x41f4000
0x41f4000
0x41f4000
```

Is this intended? I can work around it if so.

**Comment by Boyan-MILANOV** [comment]
We should be using `mappings.is_free()` here instead of `page_manager.is_unmapped()`. The page manager keeps track of page permissions, but the actual mappings are managed by the `MemMapManager`.

https://github.com/trailofbits/maat/blob/6a7b6730e3ff755e0d47f685b87effe07933b03f/src/memory/memory.cpp#L1675

**Comment by jamesd90** [comment]
Thank you! :)

**Comment by Boyan-MILANOV** [comment]
You're welcome! I've issued a patch release so that the changes are pushed on to the PyPI package. Waiting for it to build.
