### ISSUE TITLE
https://maat.re/ is down

### ISSUE THREAD

**Issue by atredis-jordan** [trailofbits/maat#176]
It seems the site containing some useful documentation is down.
https://maat.re/

This is a useful resource, and can hopefully be returned.
Even if the site can be returned, adding the documentation information into this repository could be useful, to prevent future loss.

**Comment by Boyan-MILANOV** [comment]
Hey @atredis-jordan, we've put the site back up. It's now hosted on github pages and the `maat.re` now redirects there!

**Comment by CharlesAverill** [comment]
@Boyan-MILANOV 
`maat.re` no longer redirects to github pages

**Comment by redthing1** [comment]
docs can be found here:
https://trailofbits.github.io/maat-docs/
