### ISSUE TITLE
Python3 PIP install for Apple Silicon macs

### ISSUE THREAD

**Issue by Ignacio-Freire** [trailofbits/maat#63]
Hello everyone! 

Today I tried to install PyMaat and it instantly failed with not finding a version to install.

```
$ python3 -m pip install pymaat
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pymaat (from versions: none)
ERROR: No matching distribution found for pymaat
```

Also tried with `sudo` but got the same errors

```
$ sudo -H python3 -m pip install pymaat
ERROR: Could not find a version that satisfies the requirement pymaat (from versions: none)
ERROR: No matching distribution found for pymaat
```

I'm using `pip-22.0.3` and `Python 3.8.9`

Regards

**Comment by ekilmer** [comment]
Hello, could you please paste some more information about your system, like Operating system/Linux distribution, how Python was installed, and ideally steps to how we could hopefully reproduce this behavior?

Thank you.

**Comment by Ignacio-Freire** [comment]
> Hello, could you please paste some more information about your system, like Operating system/Linux distribution, how Python was installed, and ideally any other steps to how we could hopefully reproduce this behavior?
> 
> Thank you.

Yes, the OS is Monterey V12.2.1

And that's the Python version that came out of the box. For pip I did update it by doing `python3 -m pip install --upgrade pip` after trying to install PyMaat with version `pip-20.2.1`

So to sum up, these were my steps:

1.- Try `python3 -m pip install pymaat` - Gave the error in the OP
2.- Try `sudo -H python3 -m pip install pymaat` - Gave the error in the OP
3.-  Ran `python3 -m pip install --upgrade pip`
4.- Try again `python3 -m pip install pymaat` - Gave the error in the OP
5.- Try again `sudo -H python3 -m pip install pymaat` - Gave the error in the OP

**Comment by Ignacio-Freire** [comment]
> Do you happen to have an M1 (Apple Silicon) machine? Our Python wheels are built only for x86-64.

I do actually. That might be the issue then. Are there any plans on supporting ARM64?

**Comment by Boyan-MILANOV** [comment]
We're using `cibuildwheel` to build the python packages and it looks like they support building Apple Silicon compatible wheels by cross-compiling to `arm64`: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon 

We'll try to add the `arm64` targets to our packaging workflow and get back to you!
