### ISSUE TITLE
SIGABRT on `Value.as_int()`

### ISSUE THREAD

**Issue by Rubonnek** [trailofbits/maat#73]
**Maat version:**
`master` branch at commit 1d1c0d3bbbb65d1f0621eb477abcaae817da8336

**Issue description:**
Same as title. I'm consistently getting a SIGABRT signal when running `Value.as_int()` over python.

**Steps to reproduce:**
Run the following:
```python
from maat import *
m = MaatEngine(ARCH.X64, OS.LINUX)
m.cpu.rax = Var(64, "a") # Variable "a" on 64 bits
m.cpu.rax.as_int()
```

**Comment by Boyan-MILANOV** [comment]
In your example `"a"` is a purely symbolic variable, so it can't be concretized. When calling `as_int()` the method complains that `"a"` doesn't have any concrete value in the current context, and raises an exception

``` 
var_context_exception: Trying to access variable 'a' which is unknown in context
```

We just forgot to catch that native exception in the bindings, resulting in `SIGABRT`. That'll be easy to fix. Thanks for reporting this!

**Comment by Boyan-MILANOV** [comment]
#74 fixes the issue. We now get the correct behaviour: 

```
>>> from maat import *
>>> m = MaatEngine(ARCH.X64)
>>> m.cpu.rax = Var(64, "a")
>>> m.cpu.rax.as_int()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Concretization error: Variable 'a' has no concrete value in context
```

**Comment by Rubonnek** [comment]
> In your example `"a"` is a purely symbolic variable, so it can't be concretized. When calling `as_int()` the method complains that `"a"` doesn't have any concrete value in the current context, and raises an exception
> 
> ```
> var_context_exception: Trying to access variable 'a' which is unknown in context
> ```
> 
> We just forgot to catch that native exception in the bindings, resulting in `SIGABRT`. That'll be easy to fix. Thanks for reporting this!

I'm aware -- I should've said I reported this because the message I was seeing wasn't the same as what's shown in the [DSE Values](http://maat.re/tutorials/dse.html#values) tutorial which I was following. Also the new message doesn't match what's in the tutorial either, so perhaps the text in the tutorial should be updated as well.

Thanks for the quick turnaround!

**Comment by Boyan-MILANOV** [comment]
> so perhaps the text in the tutorial should be updated as well 
Will do!
